// <auto-generated />
using CrownHotelListing.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrownHotelListing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221028001709_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrownHotelListing.Domain.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nigeria",
                            ShortName = "NGR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada",
                            ShortName = "CAD"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United States of America",
                            ShortName = "USA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "England",
                            ShortName = "ENG"
                        });
                });

            modelBuilder.Entity("CrownHotelListing.Domain.Model.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alagbaka Akure",
                            CountryId = 1,
                            Name = "Diamond Image",
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Toronto district",
                            CountryId = 2,
                            Name = "Royal",
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Washington Avenue",
                            CountryId = 3,
                            Name = "Eagles",
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Burkingham lane",
                            CountryId = 4,
                            Name = "Queen",
                            Rating = 0.0
                        });
                });

            modelBuilder.Entity("CrownHotelListing.Domain.Model.Hotel", b =>
                {
                    b.HasOne("CrownHotelListing.Domain.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
